MODEL:
  TYPE: resnest50
  DEPTH: 50
  NUM_CLASSES: 3607
  HEADS:
    NAME: "LinearHead"
    NUM_CLASSES: 3607
    IN_FEAT: 2048
    REDUCTION_DIM: 512
    POOL_LAYER: "gempool"
    CLS_LAYER: "arcface"
    MARGIN: 0.15
    SCALE: 30
BN:
  ZERO_INIT_FINAL_GAMMA: True
OPTIM:
  BASE_LR: 0.1
  LR_POLICY: cos
  STEPS: [0, 30, 60, 90]
  LR_MULT: 0.1
  MAX_EPOCH: 300
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.0001
  WARMUP_EPOCHS: 0
TRAIN:
  DATASET: plant
  SPLIT: train
  BATCH_SIZE: 32
  IM_SIZE: 512
  EVAL_PERIOD: 1
TEST:
  DATASET: plant
  SPLIT: val
  BATCH_SIZE: 32
  IM_SIZE: 512
  MAX_POSITIVE_CNT: 30000
NUM_GPUS: 1
DATA_LOADER:
  NUM_WORKERS: 8
CUDNN:
  BENCHMARK: True
OUT_DIR: ./output
INFER:
  INFER_DIR: ''
  MODEL_WEIGHTS: ''
